apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: filesystem-enigma
spec:
  dependsOn:
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: '>=v0.0.0'
  - provider: xpkg.upbound.io/upbound/provider-aws-efs
    version: v1.17.0
  - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
    version: v0.7.0
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/crossplane-by-example/filesystem-enigma
  source: github.com/upbound/project-template
