apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfsenigmas.aws.upbound.io
spec:
  claimNames:
    kind: FSEnigma
    plural: fsenigmas
  group: aws.upbound.io
  names:
    categories:
    - crossplane
    kind: XFSEnigma
    plural: xfsenigmas
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: FSEnigma is the Schema for the FSEnigma API.
        properties:
          spec:
            description: FSEnigmaSpec defines the desired state of FSEnigma.
            type: object
          status:
            description: FSEnigmaStatus defines the observed state of FSEnigma.
            properties:
              fsId:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
